### ISSUE TITLE
[refactor] 키워드 추출 기능 수정

### ISSUE THREAD

**Issue by KkomSang** [DOTOREAD/DOTOREAD-SERVER#13]
## 🐿️ 기능 설명

> 추가하려는 기능에 대해 간단히 설명해주세요

키워드 추출 기능을 수정합니다. request DTO 생성, response 통일 등의 작업을 합니다.
또한 크롤링을 파이썬에서 수행하는 것으로 변경했기에 CrawlerService를 삭제합니다.

## ✅ TODO

- [x] request dto 생성
- [x] api response 통일
- [x] 크롤링 관련 코드 삭제
- [x] LdaController 위치 변경
