### ISSUE TITLE
[feat] 메인 화면 api 구현

### ISSUE THREAD

**Issue by KkomSang** [DOTOREAD/DOTOREAD-SERVER#53]
## 🐿️ 기능 설명

> 추가하려는 기능에 대해 간단히 설명해주세요

main 화면의 api를 구현합니다.
- 읽은 북마크 수 조회 api 구현
- 기부 도토리 개수 조회 api 구현
- fresh article 조회 api 구현
- rotten article 조회 api 구현
- 스토리지 조회 api 수정 (사용/전체)

## ✅ TODO

- [x] 읽은 북마크 수 조회 api
- [x] 기부 도토리 개수 조회 api
- [x] fresh article 조회 api
- [x] rotten article 조회 api
- [x] 스토리지 조회 api (사용/전체)
