### ISSUE TITLE
[CI] CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by KkomSang** [DOTOREAD/DOTOREAD-SERVER#8]
## 🐿️ 기능 설명

> 추가하려는 기능에 대해 간단히 설명해주세요

CI/CD 파이프라인을 구축합니다. Docker와 CodeDeploy를 사용합니다. 

## ✅ TODO

- [x] Github Actions
- [x] 환경변수 설정
- [x] Docker
- [x] AWS(EC2, CodeDeploy, S3, ECR) 설정
- [x] deploy.yml 작성
- [x] appspec.yml 작성
- [x] Dokerfile 작성
- [x] 브랜치 변경
- [x] 도메인 설정(+https 설정)
- [x] RDS 생성 및 연결
